# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfKkxIDOdqKQDN9rVhteH0UYi66jXUjq
"""

def tukar(lists,i,j):
    lists[i],lists[j]=lists[j], lists[i]
    
def BubbleSort(listSaya):
    ubah = True
    x = len(listSaya)-1
    while x >= 0 and ubah:
        ubah = False
        for i in range(x,0,-1):
            if listSaya[i]<listSaya[i-1]:
                tukar(listSaya,i,i-1)
                ubah = True
        if not ubah:
            return listSaya
        x-=1

alist=[12,19,56,31,45,44,90]

sortedList = BubbleSort(alist)
print(sortedList)

sortedList.reverse()
print(sortedList)